### PR TITLE
feat!: LBPWeight type refactor

### PR DESCRIPTION
**Pull request by jak-pan**
Not sure if I did the right thing to move to types but me feel it's right @enthusiastmartin @Roznovjak WDYT

### CODE REVIEW

**Comment by enthusiastmartin** [comment]
Looks ok.

Question is : why weight is only u32 ?

**Comment by jak-pan** [comment]
> Looks ok.
> 
> Question is : why weight is only u32 ?

It's a range from 0 to 100% I don't see much point in larger weights unless we want to run LBPs for a year and have the weight change every day smoothly. Faster calc + smaller storage for each pool. It would be different for omnipool or multi asset lbp but we have only 2 tokens. Thinking also about ditching the balancer equation and augumenting XYK one with weights as we're trading two tokens. Should be much faster to compute.

**Comment by enthusiastmartin** [comment]
> 
> 
> > Looks ok.
> > Question is : why weight is only u32 ?
> 
> It's a range from 0 to 100% I don't see much point in larger weights unless we want to run LBPs for a year and have the weight change every day smoothly. Faster calc + smaller storage for each pool. It would be different for omnipool or multi asset lbp but we have only 2 tokens. Thinking also about ditching the balancer equation and augumenting XYK one with weights as we're trading two tokens. Should be much faster to compute.

Ok, my concern was mainly if it is enough. but if you think it is sufficient -then 👍

**Comment by jak-pan** [comment]
> > > Looks ok.
> > > Question is : why weight is only u32 ?
> > 
> > 
> > It's a range from 0 to 100% I don't see much point in larger weights unless we want to run LBPs for a year and have the weight change every day smoothly. Faster calc + smaller storage for each pool. It would be different for omnipool or multi asset lbp but we have only 2 tokens. Thinking also about ditching the balancer equation and augumenting XYK one with weights as we're trading two tokens. Should be much faster to compute.
> 
> Ok, my concern was mainly if it is enough. but if you think it is sufficient -then 👍

If we say 100% is 100_000_000 which we do - We have ~ 7000 days of running LBP if we have 6s blocks to run out of precision (weight is not changed by at least 1 each block) so I guess it's good enough?

**Review by enthusiastmartin — APPROVED** [review]

**Pull request merged**
